apiVersion: v1
kind: Service
metadata:
  name: shelterapp-service
spec:
  selector:
    app: shelterapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
